### ISSUE TITLE
Unable to perform database query.

### ISSUE THREAD

**Issue by zentixua** [voidpointer0x00/VoidWhitelist#14] opened 2023-03-22 11:01 UTC
Hello.  I discovered a funny thing - if no one joins to the server for a long time (more than 8 hours), then I get this error after players join:

`[ForkJoinPool.commonPool-worker-21/WARN]: [VoidWhitelist] Unable to perform a database query: The last packet successfully received from the server was 38,857,955 milliseconds ago. The last packet sent successfully to the server was 38,857,955 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.`

I have default mariadb options set.

**Comment by zentixua** [comment] 2023-03-22 11:03
I think you need to do an automatic reconnection if I understand correctly

**Comment by voidpointer0x00** [comment] 2023-03-22 11:06
Yep. That's weird that it's  not in the plugin

**Comment by zentixua** [comment] 2023-03-22 11:09
Lel 😆

**Comment by voidpointer0x00** [comment] 2023-03-22 11:10
For now you can just manually reconnect _(there's a command for that in case you changed database settings)_

I'll get to it a few hours, it's a quick fix, just gotta change two lines like this one
https://github.com/voidpointer0x00/VoidWhitelist/blob/7cb46fc05decd99058010b8379871766e56026bb/src/main/java/voidpointer/spigot/voidwhitelist/config/DbmsFactory.java#L77

**Comment by voidpointer0x00** [comment] 2023-03-22 15:28
Just fixed the code, I'm going to run two servers hopefully for about 12 hours — one running old 0.9.1 and the other one running 0.9.2 whitelist, if the issue won't reproduce I'll merge fix and release it. You can download the new 0.9.2 at [tag v0.9.2-unstable](https://github.com/voidpointer0x00/VoidWhitelist/releases/tag/v0.9.2-unstable)

**Comment by zentixua** [comment] 2023-03-22 15:33
In older version plugin was disabled due to inactivity in mariadb/mysql

for testing, you can change mariadb's `wait_timeout` to a small value, like 60 (seconds). I miss your time, heh

**Comment by voidpointer0x00** [comment] 2023-03-22 15:36
Thanks, I didn't even consider changing mariadb setting lol 🤣

**Comment by zentixua** [comment] 2023-03-22 15:39
hahah, lol

**Comment by zentixua** [comment] 2023-03-22 15:49
It seems the problem is still there. Last build

```
[VoidWhitelist] Unable to perform a database query: The last packet successfully received from the server was 71 668 milliseconds ago. The last packet sent successfully to the server was 71 668 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[17:39:39 INFO]: Disconnecting com.mojang.authlib.GameProfile@42d74db8[id=8f36620b-0a47-3fea-924f-40399aac3be4,name=Genife,properties={},legacy=false] (/91.224.96.197:42436): Вас нет в whitelist.
[17:39:39 INFO]: com.mojang.authlib.GameProfile@42d74db8[id=8f36620b-0a47-3fea-924f-40399aac3be4,name=Genife,properties={},legacy=false] (/91.224.96.197:42436) lost connection: Вас нет в whitelist.
```

Hmm, if the player tries to reconnect to the server, everything will be fine

**Comment by zentixua** [comment] 2023-03-22 15:50
(mariadb commands)
```
SET GLOBAL wait_timeout=60;
SET SESSION wait_timeout=60;
```

**Comment by voidpointer0x00** [comment] 2023-03-22 16:03
So does it fix itself even though it fails for the first time? Weird 
> Hmm, if the player tries to reconnect to the server, everything will be fine

**Comment by voidpointer0x00** [comment] 2023-03-22 17:18
> So does it fix itself even though it fails for the first time? Weird

Yep, that seems to be the case, just tested both versions. I'll look into other methods of fixing it, the most undesirable is to automatically initiate reconnection to the database in case of an error directly in the code, but it would require some architectural changes to codebase to make it look at least decent. What I'm thinking is, perhaps, a connection poll also might fix the issue

All in all, I think the current state is satisfactory: retrying to connect or just typing a command for the second time is not a big deal. And as long as there's a player online, the plugin will keep running sync tasks to SQL server every N _(30 by default)_ minutes, which will keep the connection running.

**Comment by voidpointer0x00** [comment] 2023-03-23 23:18
Fixed with PR https://github.com/voidpointer0x00/VoidWhitelist/pull/15, [release page](**url**).

There will be no need to reuse the command/reconnect to the server, the plugin will automatically try to reestablish database connection.
![image](https://user-images.githubusercontent.com/43143315/227385626-8e4eb107-3aed-4c9e-a861-d601ded8f1c8.png)

**Closed as completed by voidpointer0x00** 2023-03-23 23:18 UTC
Labels: type: bug, good first issue
